name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  unit_test_admin:
    runs-on: ubuntu-18.04
    container:
      image: node:12-alpine
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: install dependencies
        run: npm ci
      - name: run tests
        run: npm run test
  unit_test_app:
    runs-on: ubuntu-18.04
    container:
      image: golang:1.13-alpine
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: run go tests
        run: sh test.sh
  build:
    if: github.event_name == 'push'
    needs: [unit_test_admin, unit_test_app]
    runs-on: ubuntu-18.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: build and push docker image
        uses: mr-smithers-excellent/docker-build-push@v3
        with:
          image: ${{ github.repository }}
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
