name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  unit_test_admin:
    runs-on: ubuntu-18.04
    container:
      image: node:12-alpine
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm run test
  unit_test_app:
    runs-on: ubuntu-18.04
    container:
      image: golang:1.13-alpine
    steps:
      - name: Install dependencies
        run: apk update --no-cache && apk add --no-cache gcc
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run go tests
        run: go test ./... -v
  build:
    if: github.event_name == 'push'
    needs: [unit_test_admin, unit_test_app]
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and push docker image
        uses: mr-smithers-excellent/docker-build-push@v3
        with:
          image: yuzu-cms/yuzu-cms
          tag: master
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
